#!/bin/bash
set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
IFS=$'\n\t'

# Fix for a recent change in ca-certificates-utils this can be removed once upstream rootfs has been update.
# https://www.archlinux.org/news/ca-certificates-utils-20170307-1-upgrade-requires-manual-intervention/
pacman -Syuw --noconfirm
rm -f /etc/ssl/certs/ca-certificates.crt
pacman -Su --noconfirm

# Install required packages
pacman -Syu --noconfirm vim bash-completion zsh grml-zsh-config sudo avahi nss-mdns wpa_supplicant termite-terminfo
echo rpizw-rover > /etc/hostname

# Configure sudo
echo '%wheel ALL=(ALL) ALL' >> /etc/sudoers.d/wheel

# Enable the camera
sed -i 's/gpu_mem=.*/gpu_mem=128/' /boot/config.txt
grep 'start_file=start_x.elf' /boot/config.txt >/dev/null || echo 'start_file=start_x.elf' >> /boot/config.txt
grep 'fixup_file=fixup_x.dat' /boot/config.txt >/dev/null || echo 'fixup_file=fixup_x.dat' >> /boot/config.txt

# Install zero-conf to make the pi easier to find on the network
sed -i '/^hosts: /s/files dns/files mdns dns/' /etc/nsswitch.conf
ln -sf /usr/lib/systemd/system/avahi-daemon.service /etc/systemd/system/multi-user.target.wants/avahi-daemon.service

# Enable wireless, actual connection details will be configured by the user, likely over usb-serial
ln -sf /usr/lib/systemd/system/wpa_supplicant@.service /etc/systemd/system/multi-user.target.wants/wpa_supplicant@wlan0.service

cat >/etc/systemd/network/wlan0.network <<EOF
[Match]
Name=wlan0
[Network]
DHCP=yes
EOF

cat <<EOF > /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=wheel
update_config=1
fast_reauth=1
ap_scan=1
EOF

# Enable the usb serial
grep 'dtoverlay=dwc2' /boot/config.txt >/dev/null || echo 'dtoverlay=dwc2' >> /boot/config.txt
grep 'modules-load=dwc2,libcomposite' /boot/cmdline.txt >/dev/null || sed -i 's/.*rootwait.*/& modules-load=dwc2,libcomposite/' /boot/cmdline.txt
ln -sf /usr/lib/systemd/system/getty@ttyGS0.service /etc/systemd/system/getty.target.wants/getty@ttyGS0.service

# Enable hardware pwm
grep 'dtoverlay=pwm-2chan,pin=12,func=4,pin2=13,func2=4' /boot/config.txt >/dev/null || echo 'dtoverlay=pwm-2chan,pin=12,func=4,pin2=13,func2=4' >> /boot/config.txt

# Enable the rover-server to start on boot
ln -sf /etc/systemd/system/rover-server.service /etc/systemd/system/multi-user.target.wants/rover-server.service

cat >/usr/local/bin/rpizw-usb <<\EOF
#!/bin/bash
SYS="/sys/kernel/config/usb_gadget/rpizw"
ID="0x409"
STRINGS="$SYS/strings/$ID"
CONFIG="$SYS/configs/c.1"

mkdir -p "$SYS"
echo 0x1d6b > "$SYS/idVendor"  # Linux Foundation
echo 0x0104 > "$SYS/idProduct" # Multifunction Composite Gadget
echo 0x0100 > "$SYS/bcdDevice" # v1.0.0
echo 0x0200 > "$SYS/bcdUSB"    # USB2

mkdir -p "$STRINGS"
echo "fedcba9876543210" > "$STRINGS/serialnumber"
echo "Michael Daffin" > "$STRINGS/manufacturer"
echo "RPIZW USB Device" > "$STRINGS/product"

mkdir -p "$CONFIG"
echo "Config 1: ECM network" > "$CONFIG/strings/$ID/configuration"
echo 250 > "$CONFIG/MaxPower"

# Add functions here
mkdir -p "$SYS/functions/acm.usb0"
ln -s "$SYS/functions/acm.usb0" "$CONFIG/"
# End functions

ls /sys/class/udc > "$SYS/UDC"
EOF

chmod +x /usr/local/bin/rpizw-usb

cat >/etc/systemd/system/rpizw-usb.service <<\EOF
[Unit]
Description=RPIZW USB gadgets

[Service]
Type=oneshot
ExecStart=/usr/local/bin/rpizw-usb
RemainAfterExit=true

[Install]
WantedBy=multi-user.target
EOF

ln -sf /etc/systemd/system/rpizw-usb.service /etc/systemd/system/multi-user.target.wants/rpizw-usb.service

# Set zsh as the defualt shell for root and alram
chsh -s /usr/bin/zsh root
chsh -s /usr/bin/zsh alarm
touch /root/.zshrc
touch /home/alarm/.zshrc
chown alarm. /home/alarm/.zshrc
